# Download image
FROM alpine:3.8 AS downloader
RUN apk add --no-cache curl ca-certificates bash tar
WORKDIR /downloads

# Download/unpack caddy, link as generated by https://caddyserver.com/download
RUN curl -L 'https://caddyserver.com/download/linux/amd64?plugins=http.cache,http.cors,http.expires,http.git,http.realip&license=personal&telemetry=on' -o caddy.tgz
RUN tar -xzvf caddy.tgz caddy

# Download/unpack hugo, link via https://github.com/gohugoio/hugo/releases
RUN curl -L 'https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.tar.gz' -o hugo.tgz
RUN tar -xzvf hugo.tgz hugo

# App image
FROM alpine:3.8
RUN apk add --no-cache openssh-client git ca-certificates

COPY --from=downloader /downloads/caddy /caddy
COPY --from=downloader /downloads/hugo /hugo

RUN /caddy -version
RUN /caddy -plugins

EXPOSE 80 443 2015
VOLUME /root/.caddy /srv
WORKDIR /srv

ENTRYPOINT ["/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=true"]
